title: Shehzadi Aziz # your name (or website title) here
logo: "shehzadi_headshot.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  MSc in Applied Data Science from University of Essex,
  BA(Hons) in Political Culture and Social Data Science
  from University of Warwick.
  <br><br>
  Awardee of full Data Science and AI scholarship. 
  <br><br>
  Professional experience mostly in automation in the digital marketing industry.
  <br><br>
  <a href="https://www.linkedin.com/in/shehzadi-aziz-b99a54191/">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
